name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Dependencies
        run: flutter pub get

      - name: Find Isar build.gradle
        run: |
          find ~/.pub-cache -path "*isar_flutter_libs*/android/build.gradle"

      - name: Patch Isar
        shell: bash
        run: |
          FILE=$(find ~/.pub-cache -path "*isar_flutter_libs*/android/build.gradle")

          echo "PATCH FILE = $FILE"

          if [ ! -f "$FILE" ]; then
            echo "File build.gradle Isar tidak ditemukan!"
            exit 1
          fi

          # Tambah namespace jika belum ada
          if ! grep -q "namespace" "$FILE"; then
            sed -i '/android {/a\    namespace "dev.isar.isar_flutter_libs"' "$FILE"
          fi

          # Ganti compileSdkVersion menjadi 35
          sed -i 's/compileSdkVersion 30/compileSdkVersion 35/g' "$FILE"
          sed -i 's/compileSdkVersion 31/compileSdkVersion 35/g' "$FILE"
          sed -i 's/compileSdkVersion 32/compileSdkVersion 35/g' "$FILE"
          sed -i 's/compileSdkVersion 33/compileSdkVersion 35/g' "$FILE"
          sed -i 's/compileSdkVersion 34/compileSdkVersion 35/g' "$FILE"

          echo "=============================="
          cat "$FILE"
          echo "=============================="

      - name: Build APK
        run: flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DigiNews-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk