name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"

      - name: Install Dependencies
        run: flutter pub get

      - name: Install Android SDK 35
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-35"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"

      - name: Find Isar build.gradle
        run: |
          find ~/.pub-cache -name build.gradle | grep isar_flutter_libs

      - name: Patch Isar
        run: |
          FILE=$(find ~/.pub-cache -name build.gradle | grep isar_flutter_libs)

          echo "PATCH FILE = $FILE"

          if [ -z "$FILE" ]; then
            echo "Isar build.gradle tidak ditemukan!"
            exit 1
          fi

          python3 <<EOF
from pathlib import Path

file = Path("$FILE")
text = file.read_text()

if 'namespace "dev.isar.isar_flutter_libs"' not in text:
    text = text.replace(
        "android {",
        'android {\n    namespace "dev.isar.isar_flutter_libs"'
    )

text = text.replace(
    "compileSdkVersion 30",
    "compileSdkVersion 35"
)

file.write_text(text)

print(file.read_text())
EOF

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DigiNews-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk