name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"

      - name: Install Dependencies
        run: flutter pub get

      - name: Patch Isar Namespace
        run: |
          FILE="$HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android/build.gradle"

          echo "Before patch:"
          cat "$FILE"

          sed -i '/android {/a\    namespace "dev.isar.isar_flutter_libs"' "$FILE"

          echo "After patch:"
          cat "$FILE"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DigiNews-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk